### ISSUE TITLE
自动生成代码,xml中报红

### ISSUE THREAD

**Issue by wangweiping** [zoulejiu/mybatisSmartPlugin#1]
![image](https://user-images.githubusercontent.com/18497716/110745030-9f47cf00-8275-11eb-88b2-57f7179aa111.png)

**Comment by zoulejiu** [comment]
你项目设置了数据库吗，这块是idea 没有检测到，看看model 里面的名称是否和这里一直，如果是一致的应该是没问题的，直接运行看看

**Comment by wangweiping** [comment]
配置了,
![image](https://user-images.githubusercontent.com/18497716/110746564-f353b300-8277-11eb-9a8e-666f42551cb7.png)
关闭插件之后，不报红了
![image](https://user-images.githubusercontent.com/18497716/110746738-33b33100-8278-11eb-857b-8b26ee945ac4.png)

**Comment by zoulejiu** [comment]
明白，有些功能还在开发中,后续就好了

**Comment by wangweiping** [comment]
好的，期待中......

**Comment by zoulejiu** [comment]
那我关闭这个问题了

**Comment by zoulejiu** [comment]
在下一个版本已修复这个问题
